spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/iorhael/senla-config-storage

  security:
    user:
      name: config-server
      password: password

server:
  port: 8888
